// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=transaction_repository.go -destination=transaction_repository_mock.go -package=repository TransactionRepository
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/zevinza/cita-kita-transfer-service/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// ApplyTransfer mocks base method.
func (m *MockTransactionRepository) ApplyTransfer(ctx context.Context, req *model.TransferRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyTransfer", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyTransfer indicates an expected call of ApplyTransfer.
func (mr *MockTransactionRepositoryMockRecorder) ApplyTransfer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyTransfer", reflect.TypeOf((*MockTransactionRepository)(nil).ApplyTransfer), ctx, req)
}

// GetBalance mocks base method.
func (m *MockTransactionRepository) GetBalance(ctx context.Context, accountID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockTransactionRepositoryMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockTransactionRepository)(nil).GetBalance), ctx, accountID)
}

// GetIdempotencyResult mocks base method.
func (m *MockTransactionRepository) GetIdempotencyResult(ctx context.Context, key string) (*model.TransferResponse, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdempotencyResult", ctx, key)
	ret0, _ := ret[0].(*model.TransferResponse)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetIdempotencyResult indicates an expected call of GetIdempotencyResult.
func (mr *MockTransactionRepositoryMockRecorder) GetIdempotencyResult(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdempotencyResult", reflect.TypeOf((*MockTransactionRepository)(nil).GetIdempotencyResult), ctx, key)
}
